### ISSUE TITLE
The websockets doesnt run.

### ISSUE THREAD

**Issue by freskpe** [shadowk29/BinanceBalance#2]
Hi shadowk29, thank you for your work!
i found a bug in your code.
the line 289 (bm.start()) have to be moved to line 298 (before self.parent.after_idle(self.parent.after,1,self.process_queue) or your code donesnt run the websockets.

**Comment by shadowk29** [comment]
Strange, it seems to work for me as is. Can you post the error you get?

Thanks for letting me know. I will take a look tomorrow.

**Comment by freskpe** [comment]
Im no getting a error, simply do not update the data and interface but after change the lines the program run perfect. Im using python 3 on linux.

**Comment by shadowk29** [comment]
Must be a python 3 thing, I'm running 2.7. I will play with it tomorrow.
Thanks!
